# Sentencing Guidelines

In [65]:
import pandas as pd

offs = pd.read_csv(
    "/Users/clarissaache/Documents/Capstone/qsides/10_cleaned_data/offense_cleaned4.csv"
)
offence_codes = pd.read_csv(
    "/Users/clarissaache/Documents/Capstone/qsides/00_raw_data/ACIS_offence_codes.csv"
)
offence_codes

,D,CODE,T,Offense Description,NC General Statute,Offense Start Date,Offense End Date,CL,Class Start Date,Class End Date,DWI and IC Report,Max Date
0,NaN,910,F,MURDER OF AN UNBORN CHILD,14-23.2(A),20111201,99999999,??,20111201.0,99999999.0,No,20111201
1,NaN,915,F,VOL MANSLAUGHTER UNBORN CHILD,14-23.3(A),20111201,99999999,D,20111201.0,99999999.0,No,20111201
2,NaN,916,F,INV MANSLAUGHTER UNBORN CHILD,14-23.4(A),20111201,99999999,F,20111201.0,99999999.0,No,20111201
3,NaN,920,F,VOLUNTARY MANSLAUGHTER,14-18,0,99999999,E,19941001.0,19971130.0,No,19971130
4,NaN,920,F,VOLUNTARY MANSLAUGHTER,14-18,0,99999999,D,19971201.0,99999999.0,No,19971201
...,...,...,...,...,...,...,...,...,...,...,...,...
2179,NaN,9978,M,OPERATE BOAT RECKLESS MANNER,75A-10(A),20020105,99999999,2,20020105.0,99999999.0,No,20020105
2180,NaN,9979,M,CAMPAIGN CONTRIBUTION VIOL,163-278.13,20030101,20170131,2,20030101.0,20170131.0,No,20170131
2181,*,9980,T,COVERING/DISGUISING REG PLATE,20-63(G),0,19910408,NaN,NaN,NaN,No,19910408
2182,*,9984,T,IMPROPER USE OF DEALER PERMIT,20-79,0,19910408,NaN,NaN,NaN,No,19910408
2183,NaN,9999,NaN,OTHER - FREE TEXT,NaN,0,99999999,??,19941001.0,99999999.0,No,19941001

In [78]:
offence_codes[offence_codes['CODE']==5450]

,D,CODE,T,Offense Description,NC General Statute,Offense Start Date,Offense End Date,CL,Class Start Date,Class End Date,DWI and IC Report,Max Date
1495,NaN,5450,T,SPEEDING,20-141(J1),0,99999999,2,19941001.0,20131130.0,No,20131130
1496,NaN,5450,T,SPEEDING,20-141(J1),0,99999999,3,20131201.0,99999999.0,No,20131201

In [70]:
offs.shape

(26951, 38)

In [77]:
# EXAMPLE OF ONE CASE
offs[offs['case_id']==2802007060883]

,Unnamed: 0,case_id,CRRKEY,charged_offense_date,charged_offense_code,arraigned_offense_date,convicted_offense_code,offense_court_type,plea_code,verdict_code,disposition,disposition_date,judge_code,min_sentence,max_sentence,min_sentence_frame,fines,restitution,probation_len,probation_frame,suspension_len,suspension_frame,supervised_probation_flag,date to paid,monies_paid_flag,more_offense_check_flag,max_sentence_frame,plea_bargain_flag,domestic_violence_flag,active_sentence_ind,community_service_hr,offense_class,prior_record_points,judgement_file_number,judgement_file_offense_num,court_cost,min_sentence_day,max_sentence_day
18025,18025,2802007060883,280200706088300201001100,2007-07-01,1103,2007-07-01,NaN,NaN,NaN,NaN,SI,2008-02-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18026,18026,2802007060883,280200706088300351001100,2007-07-01,1103,NaN,NaN,NaN,NaN,NaN,VD,2008-07-22,KMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18027,18027,2802007060883,280200706088300652001100,2007-07-01,1132,NaN,NaN,NaN,NaN,NaN,VD,2008-07-22,KMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18028,18028,2802007060883,280200706088300753001100,2007-07-01,1132,NaN,NaN,NaN,NaN,NaN,VD,2008-07-22,KMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18029,18029,2802007060883,280200706088300854001100,2007-07-01,1118,NaN,1118.0,NaN,GU,GU,JU,2008-07-22,MEB,21.0,26.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,M,NaN,N,A,NaN,F,5.0,NaN,NaN,NaN,630.0,780.0
18030,18030,2802007060883,280200706088301455001100,2007-07-01,1118,NaN,1118.0,NaN,GU,GU,JU,2008-07-22,MEB,21.0,26.0,M,0.0,0.0,36.0,M,NaN,NaN,Y,NaN,R,Y,M,NaN,N,I,50.0,F,5.0,NaN,NaN,NaN,630.0,780.0
18031,18031,2802007060883,280200706088302156001100,2007-07-01,1118,NaN,1118.0,NaN,GU,GU,JU,2008-07-22,MEB,21.0,26.0,M,NaN,NaN,36.0,M,NaN,NaN,Y,NaN,NaN,Y,M,NaN,N,C,50.0,F,5.0,NaN,NaN,NaN,630.0,780.0
18032,18032,2802007060883,280200706088302757001100,2007-07-01,5099,NaN,NaN,NaN,NaN,NaN,PR,2009-12-01,KMB,21.0,26.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,M,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,780.0
18033,18033,2802007060883,280200706088303458001100,2007-07-01,5099,NaN,NaN,NaN,NaN,NaN,PR,2009-12-01,KMB,21.0,26.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,M,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,780.0
18034,18034,2802007060883,280200706088303859001100,2007-07-01,5099,NaN,NaN,NaN,NaN,NaN,PO,2021-02-23,LIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
print('the number of offences that have a JUDGE code: ')
print(26951-offs['judge_code'].isna().sum())

print('the number of offences that have a convicted code: ')
print(26951-offs['convicted_offense_code'].isna().sum())

# very similar

print('the number of offences that have a min sentence: ')
print(26951-offs['min_sentence'].isna().sum())

the number of offences that have a JUDGE code:
6555
the number of offences that have a convicted code:
6375
the number of offences that have a min sentence:
1793

In [67]:
cases = pd.read_csv("/Users/clarissaache/Documents/Capstone/qsides/10_cleaned_data/case_cleaned.csv")
cases.columns
#cases = cases[['case_id','Race', 'Sex', 'Attorney Type', 'Arrest Date', 'Jail Release Date']]

Index(['Unnamed: 0', 'case_id', 'County Code', 'Century', 'Year', 'Court Type',
       'Race', 'Sex', 'Type of Process Served', 'CRRIDT', 'Creation Date',
       'Service Date', 'Case Trial Date', 'Attorney Type', 'Indeictment Date',
       'Bond Type', 'Bond Amount', 'Offence Time Hour', 'Offence Minute',
       'Offence AM/PM', 'Jail Indicator', 'Jail Release Date',
       'Jail Commited Date', 'Arrest Date', 'Domestic Violence DC?',
       'Domestic Violence SpC?'],
      dtype='object')

In [64]:


case_offense = pd.merge(cases, offs, on='case_id', how='left', validate='1:m', indicator=True)
print(case_offense._merge.value_counts())

# Created RaceGender column
case_offense['RaceGender']=0
case_offense.loc[(case_offense['Sex']=='M') & (case_offense['Race']=='W'), 'RaceGender']='White Male'
case_offense.loc[(case_offense['Sex']=='F') & (case_offense['Race']=='W'),'RaceGender']='White Female'
case_offense.loc[(case_offense['Sex']=='M') & (case_offense['Race']=='B'),'RaceGender']='Black Male'
case_offense.loc[(case_offense['Sex']=='F') & (case_offense['Race']=='B'),'RaceGender']='Black Female'
case_offense.loc[(case_offense['Sex']=='M') & (case_offense['Race']=='H'),'RaceGender']='Hispanic Male'
case_offense.loc[(case_offense['Sex']=='F') & (case_offense['Race']=='H'),'RaceGender']='Hispanic Female'

NameError: name 'offs' is not defined

In [54]:
# most offences have a disposition
offs[offs.disposition.isna()]['min_sentence'] #2317

18      NaN
37      NaN
52      NaN
53      NaN
70      NaN
         ..
26933   NaN
26943   NaN
26948   NaN
26949   NaN
26950   NaN
Name: min_sentence, Length: 2317, dtype: float64

In [18]:
pd.set_option("display.max_columns", None)
offs.sample(5)

offs_codes = pd.merge(offs, offence_codes, left_on=["convicted_offense_code",'offense_class'], right_on=['CODE','CL'], how='left', validate="m:m", indicator=True)

In [20]:
# Substetting for cases that have a charge code (most do)
cases_w_charges = offs_codes.loc[~offs_codes['charged_offense_code'].isna()]
cases_w_charges

,Unnamed: 0,case_id,CRRKEY,charged_offense_date,charged_offense_code,arraigned_offense_date,convicted_offense_code,offense_court_type,plea_code,verdict_code,disposition,disposition_date,judge_code,min_sentence,max_sentence,min_sentence_frame,fines,restitution,probation_len,probation_frame,suspension_len,suspension_frame,supervised_probation_flag,date to paid,monies_paid_flag,more_offense_check_flag,max_sentence_frame,plea_bargain_flag,domestic_violence_flag,active_sentence_ind,community_service_hr,offense_class,prior_record_points,judgement_file_number,judgement_file_offense_num,court_cost,min_sentence_day,max_sentence_day,D,CODE,T,Offense Description,NC General Statute,Offense Start Date,Offense End Date,CL,Class Start Date,Class End Date,DWI and IC Report,Max Date,_merge
0,0,4202015706540,420201570654000201001100,2015-07-02,4716,NaN,NaN,NaN,NaN,NaN,VD,2017-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1,1302016052891,130201605289100201001100,2016-09-15,2322,2016-09-15,2322.0,NaN,GU,GU,JU,2017-07-10,DWA,34.0,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,1,5.0,NaN,NaN,NaN,34.0,NaN,NaN,2322.0,M,MISDEMEANOR LARCENY,14-72(A),0.0,99999999.0,1,19941001.0,99999999.0,No,19941001.0,both
2,2,2004056099,000200405609900201001100,2004-07-09,1137,2004-07-09,NaN,NaN,NaN,NaN,SI,2004-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,3,2004056099,000200405609900302001100,2004-07-09,1134,2004-07-09,NaN,NaN,NaN,NaN,SI,2004-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,4,2004056099,000200405609900451001100,2004-07-09,1137,NaN,1137.0,NaN,NG,GU,JR,2006-04-06,NLC,384.0,461.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,M,NaN,N,A,NaN,B1,13.0,NaN,NaN,NaN,11520.0,13830.0,NaN,1137.0,F,STAT RAPE/SEX OFFN DEF >=6YR,14-27.7A(A),19951201.0,20151130.0,B1,19951201.0,20151130.0,No,20151130.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26946,26946,6602018701510,660201870151000201001100,2018-02-18,5450,NaN,4418.0,NaN,RL,RS,JU,2018-08-06,WMC,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4418.0,I,IMPROPER EQUIP - SPEEDOMETER,20-123.2,19901001.0,99999999.0,NaN,NaN,NaN,No,19901001.0,both
26947,26947,6602018701510,660201870151000402001100,2018-02-18,5464,NaN,NaN,NaN,NaN,NaN,VD,2018-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26948,26948,1702021705286,170202170528600201001100,2021-06-19,5450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26949,26949,1702021705286,170202170528600402001100,2021-06-19,5446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26950,26950,1702021705286,170202170528600503001100,2021-06-19,5461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [21]:
# Which ones have different sentencing codes:
# There are 9438!! That means the funnel is super steep. Lots of cases dont get convicted for what they are charged for, plea bargin? No evidence?
cases_w_sent_code = cases_w_charges.loc[~cases_w_charges['convicted_offense_code'].isna()]
cases_w_sent_code

,Unnamed: 0,case_id,CRRKEY,charged_offense_date,charged_offense_code,arraigned_offense_date,convicted_offense_code,offense_court_type,plea_code,verdict_code,disposition,disposition_date,judge_code,min_sentence,max_sentence,min_sentence_frame,fines,restitution,probation_len,probation_frame,suspension_len,suspension_frame,supervised_probation_flag,date to paid,monies_paid_flag,more_offense_check_flag,max_sentence_frame,plea_bargain_flag,domestic_violence_flag,active_sentence_ind,community_service_hr,offense_class,prior_record_points,judgement_file_number,judgement_file_offense_num,court_cost,min_sentence_day,max_sentence_day,D,CODE,T,Offense Description,NC General Statute,Offense Start Date,Offense End Date,CL,Class Start Date,Class End Date,DWI and IC Report,Max Date,_merge
1,1,1302016052891,130201605289100201001100,2016-09-15,2322,2016-09-15,2322.0,NaN,GU,GU,JU,2017-07-10,DWA,34.0,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,1,5.0,NaN,NaN,NaN,34.0,NaN,NaN,2322.0,M,MISDEMEANOR LARCENY,14-72(A),0.0,99999999.0,1,19941001.0,99999999.0,No,19941001.0,both
4,4,2004056099,000200405609900451001100,2004-07-09,1137,NaN,1137.0,NaN,NG,GU,JR,2006-04-06,NLC,384.0,461.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,M,NaN,N,A,NaN,B1,13.0,NaN,NaN,NaN,11520.0,13830.0,NaN,1137.0,F,STAT RAPE/SEX OFFN DEF >=6YR,14-27.7A(A),19951201.0,20151130.0,B1,19951201.0,20151130.0,No,20151130.0,both
5,5,2004056099,000200405609900952001100,2004-07-09,1134,NaN,1134.0,NaN,NG,GU,JR,2006-04-06,NLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,N,NaN,NaN,E,NaN,2.004056e+09,51.0,NaN,NaN,NaN,NaN,1134.0,F,SEX OFFENSE - PARENTAL ROLE,14-27.7(A),0.0,20151130.0,E,19941001.0,20151130.0,No,20151130.0,both
6,6,2004056099,000200405609901153001100,2004-07-09,1118,NaN,1118.0,NaN,NG,GU,JR,2006-04-06,NLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,F,NaN,2.004056e+09,51.0,NaN,NaN,NaN,NaN,1118.0,F,INDECENT LIBERTIES WITH CHILD,14-202.1,0.0,99999999.0,F,19941001.0,99999999.0,No,19941001.0,both
14,14,5302017701197,530201770119700201001100,2017-03-19,4454,NaN,4450.0,NaN,RL,RS,WC,2017-03-31,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4450.0,I,SPEEDING,20-141(B),19860901.0,99999999.0,NaN,NaN,NaN,No,19860901.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26940,26940,5002019056774,500201905677400351001100,2019-11-18,2509,NaN,2599.0,NaN,GL,GL,JU,2020-03-05,KOG,29.0,47.0,M,NaN,NaN,18.0,M,NaN,NaN,Y,2021-09-05,N,NaN,M,NaN,NaN,I,NaN,I,4.0,NaN,NaN,NaN,870.0,1410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26941,26941,8902018702385,890201870238500201001100,2018-02-09,5450,NaN,4418.0,NaN,RL,RS,JU,2019-01-11,NHG,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4418.0,I,IMPROPER EQUIP - SPEEDOMETER,20-123.2,19901001.0,99999999.0,NaN,NaN,NaN,No,19901001.0,both
26942,26942,2018706924,000201870692400201001100,2018-06-25,5450,NaN,4418.0,NaN,RL,RS,JU,2019-06-14,KWO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4418.0,I,IMPROPER EQUIP - SPEEDOMETER,20-123.2,19901001.0,99999999.0,NaN,NaN,NaN,No,19901001.0,both
26945,26945,7702019000221,770201900022100201001100,2019-02-02,4725,NaN,4725.0,NaN,GU,GU,JU,2019-02-25,BLC,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-31,N,NaN,NaN,NaN,NaN,C,NaN,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4725.0,T,DWLR NOT IMPAIRED REV,20-28(A),20151201.0,99999999.0,3,20151201.0,99999999.0,No,20151201.0,both
26946,26946,6602018701510,660201870151000201001100,2018-02-18,5450,NaN,4418.0,NaN,RL,RS,JU,2018-08-06,WMC,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4418.0,I,IMPROPER EQUIP - SPEEDOMETER,20-123.2,19901001.0,99999999.0,NaN,NaN,NaN,No,19901001.0,both

In [22]:
# Check whether the sentences are given only to the cases that have a "convicted offence code" (funnel)
cases_ready_chart = cases_w_sent_code.loc[~cases_w_sent_code['min_sentence_day'].isna()]
cases_ready_chart = cases_ready_chart.loc[~cases_ready_chart['prior_record_points'].isna()]
cases_ready_chart = cases_ready_chart[
    [
        "case_id",
        "convicted_offense_code",
        "charged_offense_date",
        "plea_code",
        "verdict_code",
        "disposition",
        "prior_record_points",
        "offense_class",
        "CL",
        "Offense Description",
        "min_sentence_day",
        "max_sentence_day",
    ]
]
cases_ready_chart

,case_id,convicted_offense_code,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day
1,1302016052891,2322.0,2016-09-15,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,34.0,NaN
4,2004056099,1137.0,2004-07-09,NG,GU,JR,13.0,B1,B1,STAT RAPE/SEX OFFN DEF >=6YR,11520.0,13830.0
44,902017052358,3872.0,2017-05-17,GU,GU,JU,5.0,A1,A1,DV PROTECTIVE ORDER VIOL (M),150.0,NaN
78,4302017053975,2390.0,2017-11-26,GU,GU,JU,1.0,1,1,UNAUTHORIZED USE OF MOTOR VEH,45.0,NaN
109,4002015070103,2336.0,2015-03-10,GA,GL,JU,0.0,H,H,LARCENY FROM THE PERSON,180.0,510.0
...,...,...,...,...,...,...,...,...,...,...,...,...
26833,4202018050626,5328.0,2018-02-13,GU,GU,JU,5.0,1,1,COMMUNICATING THREATS,120.0,NaN
26881,1002017092143,5361.0,2017-11-05,GU,GU,JU,0.0,A1,A1,INTERFERE EMERG COMMUNICATION,60.0,NaN
26898,1102014703366,5310.0,2014-07-01,GU,GU,JU,0.0,2,2,RESISTING PUBLIC OFFICER,30.0,NaN
26920,1002018088389,3401.0,2018-08-14,GU,GU,JU,5.0,1,1,POSSESS DRUG PARAPHERNALIA,3.0,NaN
26940,5002019056774,2599.0,2019-11-18,GL,GL,JU,4.0,I,NaN,NaN,870.0,1410.0

In [23]:
# Subste for felonies only (we will make the misdemeanors work later LOL)
# NOPE no subsetting anymore, we got misdemeanors too
offense=cases_ready_chart

In [24]:
offense['offense_type'] = 'Felony'
offense.loc[offense['offense_class'].isin(['1','2','3','A1']),'offense_type'] = 'Misdemeanor'

# Part 2: We try to fit into the sentencing grid boxes

In [25]:
# code prior points
offense['prior_points_range'] = 0
for index, row in offense.iterrows():
    point = row['prior_record_points']
    if row['offense_type'] == 'felony':
        if (point >=0) & (point <=1):
            offense.loc[index,'prior_points_range'] = 1
        elif (point >=2) & (point <=5):
            offense.loc[index,'prior_points_range'] = 2
        elif (point >=6) & (point <=9):
            offense.loc[index,'prior_points_range'] = 3
        elif (point >=10) & (point <=13):
            offense.loc[index,'prior_points_range'] = 4
        elif (point >=14) & (point <=17):
            offense.loc[index,'prior_points_range'] = 5
        elif point>=18:
            offense.loc[index,'prior_points_range'] = 6
    else:
        if(point ==0):
            offense.loc[index,'prior_points_range'] = 1
        elif (point >=1) & (point <=4):
            offense.loc[index,'prior_points_range'] = 2
        elif (point >=5):
            offense.loc[index,'prior_points_range'] = 3

offense.sample(5)

,case_id,convicted_offense_code,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range
11226,3102019054690,2599.0,2019-05-30,GL,GL,JU,1.0,1,NaN,NaN,45.0,NaN,Misdemeanor,2
14479,4202017051185,3568.0,2017-04-04,GL,GU,JU,1.0,I,I,POSSESS HEROIN,120.0,420.0,Felony,2
26611,2016051413,1389.0,2016-03-21,GU,GU,JU,0.0,A1,A1,ASSAULT ON A FEMALE,19.0,NaN,Misdemeanor,1
6117,4802016056443,3538.0,2016-11-20,GU,GU,JU,5.0,1,1,SIMPLE POSSESS SCH IV CS (M),30.0,NaN,Misdemeanor,3
25221,7802019051820,5310.0,2019-07-02,GU,GU,JU,1.0,2,2,RESISTING PUBLIC OFFICER,45.0,NaN,Misdemeanor,2

In [26]:
offense

,case_id,convicted_offense_code,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range
1,1302016052891,2322.0,2016-09-15,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,34.0,NaN,Misdemeanor,3
4,2004056099,1137.0,2004-07-09,NG,GU,JR,13.0,B1,B1,STAT RAPE/SEX OFFN DEF >=6YR,11520.0,13830.0,Felony,3
44,902017052358,3872.0,2017-05-17,GU,GU,JU,5.0,A1,A1,DV PROTECTIVE ORDER VIOL (M),150.0,NaN,Misdemeanor,3
78,4302017053975,2390.0,2017-11-26,GU,GU,JU,1.0,1,1,UNAUTHORIZED USE OF MOTOR VEH,45.0,NaN,Misdemeanor,2
109,4002015070103,2336.0,2015-03-10,GA,GL,JU,0.0,H,H,LARCENY FROM THE PERSON,180.0,510.0,Felony,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26833,4202018050626,5328.0,2018-02-13,GU,GU,JU,5.0,1,1,COMMUNICATING THREATS,120.0,NaN,Misdemeanor,3
26881,1002017092143,5361.0,2017-11-05,GU,GU,JU,0.0,A1,A1,INTERFERE EMERG COMMUNICATION,60.0,NaN,Misdemeanor,1
26898,1102014703366,5310.0,2014-07-01,GU,GU,JU,0.0,2,2,RESISTING PUBLIC OFFICER,30.0,NaN,Misdemeanor,1
26920,1002018088389,3401.0,2018-08-14,GU,GU,JU,5.0,1,1,POSSESS DRUG PARAPHERNALIA,3.0,NaN,Misdemeanor,3
26940,5002019056774,2599.0,2019-11-18,GL,GL,JU,4.0,I,NaN,NaN,870.0,1410.0,Felony,2

In [27]:
sentencing_grid = pd.read_csv('/Users/clarissaache/Documents/Capstone/qsides/00_raw_data/punishment_grid_db.csv')
sentencing_grid

,crime_type,sg_class,sg_prior_record_level,sg_disposition,sg_MIN_min,sg_MIN_max,sg_punishment,severity_rank,sg_MAX_min,sg_MAX_max
0,Misdemeanor,3,1,NaN,1.000000e+00,1.000000e+01,C,1,NaN,NaN
1,Misdemeanor,3,2,NaN,1.000000e+00,1.500000e+01,C/I,2,NaN,NaN
2,Misdemeanor,3,3,NaN,1.000000e+00,2.000000e+01,C/I/A,3,NaN,NaN
3,Misdemeanor,2,1,NaN,1.000000e+00,3.000000e+01,C,4,NaN,NaN
4,Misdemeanor,2,2,NaN,1.000000e+00,4.500000e+01,C/I,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
187,Felony,A,5,Presumptive,3.000000e+12,3.000000e+12,A,188,NaN,NaN
188,Felony,A,5,Aggravated,3.000000e+12,3.000000e+12,A,189,NaN,NaN
189,Felony,A,6,Mitigated,3.000000e+12,3.000000e+12,A,190,NaN,NaN
190,Felony,A,6,Presumptive,3.000000e+12,3.000000e+12,A,191,NaN,NaN
191,Felony,A,6,Aggravated,3.000000e+12,3.000000e+12,A,192,NaN,NaN

In [28]:
# merge cases that have complete info and sentence grid 
grid = pd.merge(offense, sentencing_grid, left_on=['offense_type','offense_class', 'prior_points_range'], right_on=['crime_type','sg_class', 'sg_prior_record_level'], validate="m:m", indicator=True)

In [55]:
grid['race']

KeyError: 'race'

In [29]:
grid['MIN_min_diff']= grid['min_sentence_day']-grid['sg_MIN_min']
grid['MIN_max_diff']= grid['min_sentence_day']-grid['sg_MIN_max']
grid

,case_id,convicted_offense_code,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range,crime_type,sg_class,sg_prior_record_level,sg_disposition,sg_MIN_min,sg_MIN_max,sg_punishment,severity_rank,sg_MAX_min,sg_MAX_max,_merge,MIN_min_diff,MIN_max_diff
0,1302016052891,2322.0,2016-09-15,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,34.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,33.0,-86.0
1,4002009718124,5418.0,2009-07-25,GU,GU,JU,5.0,1,1,DWLR,60.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,59.0,-60.0
2,9102016201538,2322.0,2016-01-24,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,100.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,99.0,-20.0
3,3302014739887,2322.0,2014-11-26,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,120.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,119.0,0.0
4,9302018700250,5584.0,2018-02-10,GU,GU,JU,5.0,1,1,HIT/RUN LEAVE SCENE PROP DAM,2.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,1.0,-118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,3302016055781,1222.0,2016-06-16,GU,GU,JU,2.0,D,D,ROBBERY WITH DANGEROUS WEAPON,1380.0,2040.0,Felony,2,Felony,D,2,Presumptive,1770.0,2190.0,A,107,NaN,NaN,both,-390.0,-810.0
2057,3302016055781,1222.0,2016-06-16,GU,GU,JU,2.0,D,D,ROBBERY WITH DANGEROUS WEAPON,1380.0,2040.0,Felony,2,Felony,D,2,Aggravated,2190.0,2760.0,A,108,NaN,NaN,both,-810.0,-1380.0
2058,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Mitigated,4320.0,5760.0,A,157,NaN,NaN,both,1440.0,0.0
2059,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Presumptive,5760.0,7200.0,A,158,NaN,NaN,both,0.0,-1440.0
2060,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Aggravated,7200.0,9000.0,A,159,NaN,NaN,both,-1440.0,-3240.0

In [30]:
# Fit cases into SUB boxes of the sentencing grid
grid['MIN_sentence_allocated_correctly']= 0
grid.loc[(grid['MIN_min_diff']>=0) & (grid['MIN_max_diff']<0) ,'MIN_sentence_allocated_correctly']=1
grid

,case_id,convicted_offense_code,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range,crime_type,sg_class,sg_prior_record_level,sg_disposition,sg_MIN_min,sg_MIN_max,sg_punishment,severity_rank,sg_MAX_min,sg_MAX_max,_merge,MIN_min_diff,MIN_max_diff,MIN_sentence_allocated_correctly
0,1302016052891,2322.0,2016-09-15,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,34.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,33.0,-86.0,1
1,4002009718124,5418.0,2009-07-25,GU,GU,JU,5.0,1,1,DWLR,60.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,59.0,-60.0,1
2,9102016201538,2322.0,2016-01-24,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,100.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,99.0,-20.0,1
3,3302014739887,2322.0,2014-11-26,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,120.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,119.0,0.0,0
4,9302018700250,5584.0,2018-02-10,GU,GU,JU,5.0,1,1,HIT/RUN LEAVE SCENE PROP DAM,2.0,NaN,Misdemeanor,3,Misdemeanor,1,3,NaN,1.0,120.0,C/I/A,9,NaN,NaN,both,1.0,-118.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,3302016055781,1222.0,2016-06-16,GU,GU,JU,2.0,D,D,ROBBERY WITH DANGEROUS WEAPON,1380.0,2040.0,Felony,2,Felony,D,2,Presumptive,1770.0,2190.0,A,107,NaN,NaN,both,-390.0,-810.0,0
2057,3302016055781,1222.0,2016-06-16,GU,GU,JU,2.0,D,D,ROBBERY WITH DANGEROUS WEAPON,1380.0,2040.0,Felony,2,Felony,D,2,Aggravated,2190.0,2760.0,A,108,NaN,NaN,both,-810.0,-1380.0,0
2058,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Mitigated,4320.0,5760.0,A,157,NaN,NaN,both,1440.0,0.0,0
2059,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Presumptive,5760.0,7200.0,A,158,NaN,NaN,both,0.0,-1440.0,1
2060,9102020204099,1107.0,2018-07-31,GU,GU,JU,0.0,B1,B1,STATUTORY RAPE OF CHILD <= 15,5760.0,8730.0,Felony,1,Felony,B1,1,Aggravated,7200.0,9000.0,A,159,NaN,NaN,both,-1440.0,-3240.0,0

In [31]:
# Check proportion of cases that follow the rulesss
correct_allocations = grid.loc[grid['MIN_sentence_allocated_correctly']==1]

# remove duplicates in offense
correct_allocations = correct_allocations.groupby(['case_id', 'convicted_offense_code']).first()
correct_allocations

,,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range,crime_type,sg_class,sg_prior_record_level,sg_disposition,sg_MIN_min,sg_MIN_max,sg_punishment,severity_rank,sg_MAX_min,sg_MAX_max,_merge,MIN_min_diff,MIN_max_diff,MIN_sentence_allocated_correctly
case_id,convicted_offense_code,,,,,,,,,,,,,,,,,,,,,,,,,,
2004056099,1137.0,2004-07-09,NG,GU,JR,13.0,B1,B1,STAT RAPE/SEX OFFN DEF >=6YR,11520.0,13830.0,Felony,3,Felony,B1,3,Aggravated,9510.0,11910.0,A,165,NaN,NaN,both,2010.0,-390.0,1
2015055486,2699.0,2015-10-08,GU,GU,JU,1.0,1,None,None,30.0,NaN,Misdemeanor,2,Misdemeanor,1,2,None,1.0,45.0,C/I/A,8,NaN,NaN,both,29.0,-15.0,1
2016051413,1389.0,2016-03-21,GU,GU,JU,0.0,A1,A1,ASSAULT ON A FEMALE,19.0,NaN,Misdemeanor,1,Misdemeanor,A1,1,None,1.0,60.0,C/I/A,10,NaN,NaN,both,18.0,-41.0,1
2016056204,1389.0,2016-12-10,GU,GU,JU,5.0,A1,A1,ASSAULT ON A FEMALE,100.0,NaN,Misdemeanor,3,Misdemeanor,A1,3,None,1.0,150.0,C/I/A,12,NaN,NaN,both,99.0,-50.0,1
2017056796,2321.0,2017-12-15,GU,GU,JU,4.0,H,H,FELONY LARCENY,120.0,420.0,Felony,2,Felony,H,2,Mitigated,120.0,180.0,I/A,34,NaN,NaN,both,0.0,-60.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9802018051508,2912.0,2018-08-22,NC,GL,JU,6.0,2,None,None,45.0,NaN,Misdemeanor,3,Misdemeanor,2,3,None,1.0,60.0,C/I/A,6,NaN,NaN,both,44.0,-15.0,1
9802019050697,3447.0,2017-05-09,GL,GU,JU,1.0,H,H,SELL SCH IV CS,150.0,450.0,Felony,2,Felony,H,2,Mitigated,120.0,180.0,I/A,34,NaN,NaN,both,30.0,-30.0,1
9902015000351,2322.0,2015-11-03,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,15.0,NaN,Misdemeanor,3,Misdemeanor,1,3,None,1.0,120.0,C/I/A,9,NaN,NaN,both,14.0,-105.0,1
9902016050438,9968.0,2016-03-21,GU,GU,JU,5.0,I,I,MAINTN VEH/DWELL/PLACE CS (F),180.0,510.0,Felony,3,Felony,I,3,Aggravated,180.0,240.0,I,21,NaN,NaN,both,0.0,-60.0,1
9902018050173,2212.0,2018-01-02,GU,GU,JU,2.0,H,H,BREAKING AND OR ENTERING (F),240.0,570.0,Felony,2,Felony,H,2,Aggravated,240.0,300.0,I/A,36,NaN,NaN,both,0.0,-60.0,1

In [32]:
felony = correct_allocations[correct_allocations['offense_type']=='Felony']

In [33]:
# check duplicates
df = felony.groupby(['case_id', 'convicted_offense_code']).size().reset_index(name='Freq')
df[df['Freq']>1]

Empty DataFrame
Columns: [case_id, convicted_offense_code, Freq]
Index: []

In [34]:
# remove duplicates
offense = offense.groupby(['case_id', 'convicted_offense_code']).first()
offense

,,charged_offense_date,plea_code,verdict_code,disposition,prior_record_points,offense_class,CL,Offense Description,min_sentence_day,max_sentence_day,offense_type,prior_points_range
case_id,convicted_offense_code,,,,,,,,,,,,
2004056099,1137.0,2004-07-09,NG,GU,JR,13.0,B1,B1,STAT RAPE/SEX OFFN DEF >=6YR,11520.0,13830.0,Felony,3
2012006483,5418.0,2012-08-25,GU,GU,JU,5.0,1,1,DWLR,120.0,NaN,Misdemeanor,3
2015050478,2322.0,2015-01-22,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,120.0,NaN,Misdemeanor,3
2015052362,2214.0,2015-05-07,GL,GL,JU,14.0,1,1,BREAKING OR ENTERING (M),120.0,NaN,Misdemeanor,3
2015055486,2699.0,2015-10-08,GU,GU,JU,1.0,1,None,None,30.0,NaN,Misdemeanor,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9802018051508,2912.0,2018-08-22,NC,GL,JU,6.0,2,None,None,45.0,NaN,Misdemeanor,3
9802019050697,3447.0,2017-05-09,GL,GU,JU,1.0,H,H,SELL SCH IV CS,150.0,450.0,Felony,2
9902015000351,2322.0,2015-11-03,GU,GU,JU,5.0,1,1,MISDEMEANOR LARCENY,15.0,NaN,Misdemeanor,3
9902016050438,9968.0,2016-03-21,GU,GU,JU,5.0,I,I,MAINTN VEH/DWELL/PLACE CS (F),180.0,510.0,Felony,3
9902018050173,2212.0,2018-01-02,GU,GU,JU,2.0,H,H,BREAKING AND OR ENTERING (F),240.0,570.0,Felony,2

In [39]:

#offense.drop('_merge', axis=1, inplace=True)
#correct_allocations.drop('_merge', axis=1, inplace=True)
all_df = pd.merge(offense, correct_allocations, on=["case_id", "convicted_offense_code"], how='left', indicator=True).reset_index()

all_df._merge.value_counts()

both          732
left_only     524
right_only      0
Name: _merge, dtype: int64

# Plots

In [46]:
all_df['case_id']

0          2004056099
1          2012006483
2          2015050478
3          2015052362
4          2015055486
            ...
1251    9802018051508
1252    9802019050697
1253    9902015000351
1254    9902016050438
1255    9902018050173
Name: case_id, Length: 1256, dtype: int64

In [41]:
all_df.loc[all_df['case_id']==2202017000551]

,case_id,convicted_offense_code,charged_offense_date_x,plea_code_x,verdict_code_x,disposition_x,prior_record_points_x,offense_class_x,CL_x,Offense Description_x,min_sentence_day_x,max_sentence_day_x,offense_type_x,prior_points_range_x,charged_offense_date_y,plea_code_y,verdict_code_y,disposition_y,prior_record_points_y,offense_class_y,CL_y,Offense Description_y,min_sentence_day_y,max_sentence_day_y,offense_type_y,prior_points_range_y,crime_type,sg_class,sg_prior_record_level,sg_disposition,sg_MIN_min,sg_MIN_max,sg_punishment,severity_rank,sg_MAX_min,sg_MAX_max,MIN_min_diff,MIN_max_diff,MIN_sentence_allocated_correctly,_merge
228,2202017000551,4725.0,2017-04-08,GU,GU,JU,5.0,3,3,DWLR NOT IMPAIRED REV,20.0,NaN,Misdemeanor,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only